spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Coding/Java/inflearn/jpa-inf/data-jpa/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false # System.out
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false # OSIV

logging:
  level:
    org.hibernate.SQL: debug # logger
#    org.hibernate.type: trace